// ============================================================
// elements-db.js — Universal Venue Floor Plan Builder
// Primavera Events Group
// All globals, no ES modules.
// ============================================================

// ============================================================
// ELEMENT_CATEGORIES — metadata for toolbox grouping
// REQUIRED by app.js _buildToolbox() — DO NOT REMOVE
// ============================================================
window.ELEMENT_CATEGORIES = {
  mobiliario:       { label: 'Mobiliario',         icon: 'fa-chair',           color: '#b45309' },
  estructuras:      { label: 'Estructuras',         icon: 'fa-building',        color: '#374151' },
  accesos:          { label: 'Accesos',             icon: 'fa-door-open',       color: '#1d4ed8' },
  entretenimiento:  { label: 'Entretenimiento',     icon: 'fa-music',           color: '#7c3aed' },
  decoracion:       { label: 'Decoración',          icon: 'fa-wand-magic-sparkles', color: '#be185d' },
  proveedores:      { label: 'Proveedores',         icon: 'fa-store',           color: '#065f46' },
  flujo_invitados:  { label: 'Flujo Invitados',     icon: 'fa-person-walking',  color: '#0ea5e9' },
  flujo_proveedores:{ label: 'Flujo Proveedores',   icon: 'fa-truck',           color: '#f59e0b' },
  flujo_staff:      { label: 'Flujo Staff',         icon: 'fa-user-tie',        color: '#10b981' }
};

window.ELEMENTS_CATALOG = [
{
    type: 'stage',
    name: 'Escenario/Templete',
    category: 'entretenimiento',
    icon: 'fa-star',
    defaultW: 6,
    defaultH: 4,
    shape: 'rect',
    color: '#5c3d2e',
    defaultChairs: 0,
    description: 'Escenario o templete para presentaciones.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'table_round',
    name: 'Mesa Redonda (10p)',
    category: 'mobiliario',
    icon: 'fa-circle',
    defaultW: 1.6,
    defaultH: 1.6,
    shape: 'circle',
    color: '#b45309',
    defaultChairs: 10,
    description: 'Mesa redonda para 10 personas.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_square',
    name: 'Mesa Cuadrada (10p)',
    category: 'mobiliario',
    icon: 'fa-square',
    defaultW: 1.6,
    defaultH: 1.6,
    shape: 'square',
    color: '#92400e',
    defaultChairs: 10,
    description: 'Mesa cuadrada para 10 personas.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_marble_round',
    name: 'Mesa Mármol Redonda',
    category: 'mobiliario',
    icon: 'fa-circle',
    defaultW: 1.6,
    defaultH: 1.6,
    shape: 'circle',
    color: '#e2e8f0',
    defaultChairs: 10,
    description: 'Mesa de mármol redonda para 10 personas.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_marble_square',
    name: 'Mesa Mármol Cuadrada',
    category: 'mobiliario',
    icon: 'fa-square',
    defaultW: 1.6,
    defaultH: 1.6,
    shape: 'square',
    color: '#cbd5e1',
    defaultChairs: 10,
    description: 'Mesa de mármol cuadrada para 10 personas.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_campirana',
    name: 'Mesa Campirana Madera',
    category: 'mobiliario',
    icon: 'fa-table',
    defaultW: 1.6,
    defaultH: 1.6,
    shape: 'rect',
    color: '#78350f',
    defaultChairs: 10,
    description: 'Mesa campirana de madera.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_rectangular',
    name: 'Mesa Rectangular Madera',
    category: 'mobiliario',
    icon: 'fa-table-columns',
    defaultW: 2.4,
    defaultH: 0.8,
    shape: 'rect',
    color: '#92400e',
    defaultChairs: 10,
    description: 'Mesa rectangular de madera.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_imperial',
    name: 'Mesa Imperial (tablones)',
    category: 'mobiliario',
    icon: 'fa-grip-horizontal',
    defaultW: 7.2,
    defaultH: 0.8,
    shape: 'imperial',
    color: '#5c3d2e',
    defaultChairs: 30,
    description: 'Mesa imperial con tablones (ajustable).',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_periquera',
    name: 'Periquera Alta',
    category: 'mobiliario',
    icon: 'fa-circle-notch',
    defaultW: 0.7,
    defaultH: 0.7,
    shape: 'circle',
    color: '#b45309',
    defaultChairs: 4,
    description: 'Mesa periquera alta.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_umbrella',
    name: 'Mesa con Sombrilla',
    category: 'mobiliario',
    icon: 'fa-umbrella',
    defaultW: 2,
    defaultH: 2,
    shape: 'circle',
    color: '#0369a1',
    defaultChairs: 6,
    description: 'Mesa exterior con sombrilla.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_kids',
    name: 'Mesa Infantil',
    category: 'mobiliario',
    icon: 'fa-child',
    defaultW: 1,
    defaultH: 1,
    shape: 'square',
    color: '#7c3aed',
    defaultChairs: 8,
    description: 'Mesa para niños.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'lounge_set',
    name: 'Sala Lounge',
    category: 'mobiliario',
    icon: 'fa-couch',
    defaultW: 3,
    defaultH: 2.5,
    shape: 'rect',
    color: '#be185d',
    defaultChairs: 5,
    description: 'Juego de muebles lounge.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_cake',
    name: 'Mesa de Pastel',
    category: 'mobiliario',
    icon: 'fa-cake-candles',
    defaultW: 2,
    defaultH: 0.8,
    shape: 'rect',
    color: '#f472b6',
    defaultChairs: 0,
    description: 'Mesa de pastel o postres.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_gifts',
    name: 'Mesa de Regalos',
    category: 'mobiliario',
    icon: 'fa-gift',
    defaultW: 2,
    defaultH: 0.8,
    shape: 'rect',
    color: '#a855f7',
    defaultChairs: 0,
    description: 'Mesa para regalos.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_candy',
    name: 'Mesa de Dulces/Barra Mix',
    category: 'mobiliario',
    icon: 'fa-candy-cane',
    defaultW: 2,
    defaultH: 0.8,
    shape: 'rect',
    color: '#ec4899',
    defaultChairs: 0,
    description: 'Mesa de dulces o barra de mezclas.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_honor_xv',
    name: 'Mesa Honor XV',
    category: 'mobiliario',
    icon: 'fa-crown',
    defaultW: 1.2,
    defaultH: 3.5,
    shape: 'rect',
    color: '#f472b6',
    defaultChairs: 10,
    description: 'Mesa de honor para quinceañera.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_honor_bride',
    name: 'Mesa Novios (Rey & Reyna)',
    category: 'mobiliario',
    icon: 'fa-rings-wedding',
    defaultW: 1.2,
    defaultH: 3.5,
    shape: 'rect',
    color: '#c9a96e',
    defaultChairs: 2,
    description: 'Mesa de novios / pareja de honor.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_honor_king',
    name: 'Sillones Imperiales',
    category: 'mobiliario',
    icon: 'fa-throne',
    defaultW: 1,
    defaultH: 1,
    shape: 'rect',
    color: '#c9a96e',
    defaultChairs: 2,
    description: 'Sillones imperiales / tronos.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_shots',
    name: 'Carrito de Shots',
    category: 'mobiliario',
    icon: 'fa-wine-glass',
    defaultW: 0.8,
    defaultH: 1.2,
    shape: 'rect',
    color: '#7c3aed',
    defaultChairs: 0,
    description: 'Carrito de shots y bebidas.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'table_buffet',
    name: 'Mesa de Buffet',
    category: 'mobiliario',
    icon: 'fa-server',
    defaultW: 2.4,
    defaultH: 0.8,
    shape: 'rect',
    color: '#374151',
    defaultChairs: 0,
    description: 'Mesa de buffet o estación de comida.',
    layer: 'mobiliario',
    planoOnly: false
  },
{
    type: 'dancefloor',
    name: 'Pista de Baile',
    category: 'entretenimiento',
    icon: 'fa-music',
    defaultW: 5,
    defaultH: 5,
    shape: 'dancefloor',
    color: '#820ad1',
    defaultChairs: 0,
    description: 'Pista de baile estándar.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'dancefloor_pixel',
    name: 'Pista Pixel LED',
    category: 'entretenimiento',
    icon: 'fa-lightbulb',
    defaultW: 5,
    defaultH: 5,
    shape: 'dancefloor',
    color: '#4f46e5',
    defaultChairs: 0,
    description: 'Pista pixel LED interactiva.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'dancefloor_marble',
    name: 'Pista Mármol/Madera',
    category: 'entretenimiento',
    icon: 'fa-shapes',
    defaultW: 5,
    defaultH: 5,
    shape: 'dancefloor',
    color: '#1e293b',
    defaultChairs: 0,
    description: 'Pista de mármol o madera premium.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'dj_booth',
    name: 'Cabina de DJ',
    category: 'entretenimiento',
    icon: 'fa-headphones',
    defaultW: 3,
    defaultH: 1.5,
    shape: 'trapezoid',
    color: '#0d0c1d',
    defaultChairs: 0,
    description: 'Cabina de DJ.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'photobooth_360',
    name: 'Cabina 360°',
    category: 'entretenimiento',
    icon: 'fa-camera-rotate',
    defaultW: 3,
    defaultH: 3,
    shape: 'circle',
    color: '#1e3a8a',
    defaultChairs: 0,
    description: 'Cabina fotográfica 360 grados.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'photobooth_mirror',
    name: 'Espejo Selfie',
    category: 'entretenimiento',
    icon: 'fa-mirror',
    defaultW: 1.5,
    defaultH: 0.5,
    shape: 'rect',
    color: '#e2e8f0',
    defaultChairs: 0,
    description: 'Espejo selfie interactivo.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'photobooth_inflatable',
    name: 'Cabina Inflable',
    category: 'entretenimiento',
    icon: 'fa-box',
    defaultW: 3,
    defaultH: 3,
    shape: 'rect',
    color: '#0369a1',
    defaultChairs: 0,
    description: 'Cabina fotográfica inflable.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'giant_letters',
    name: 'Letras Gigantes',
    category: 'entretenimiento',
    icon: 'fa-font',
    defaultW: 4,
    defaultH: 1,
    shape: 'rect',
    color: '#f59e0b',
    defaultChairs: 0,
    description: 'Letras gigantes decorativas.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'heart_illuminated',
    name: 'Corazón Iluminado',
    category: 'entretenimiento',
    icon: 'fa-heart',
    defaultW: 1.5,
    defaultH: 1.5,
    shape: 'rect',
    color: '#ef4444',
    defaultChairs: 0,
    description: 'Corazón iluminado decorativo.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'sparklers',
    name: 'Chisperos',
    category: 'entretenimiento',
    icon: 'fa-fire',
    defaultW: 0.5,
    defaultH: 0.5,
    shape: 'circle',
    color: '#f97316',
    defaultChairs: 0,
    description: 'Chisperos / fuegos artificiales pequeños.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'red_carpet',
    name: 'Alfombra Roja',
    category: 'entretenimiento',
    icon: 'fa-scroll',
    defaultW: 1,
    defaultH: 4,
    shape: 'rect',
    color: '#dc2626',
    defaultChairs: 0,
    description: 'Alfombra roja de recepción.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'robot_led',
    name: 'Robot de LEDs',
    category: 'entretenimiento',
    icon: 'fa-robot',
    defaultW: 1,
    defaultH: 1,
    shape: 'rect',
    color: '#6366f1',
    defaultChairs: 0,
    description: 'Robot LED para entretenimiento.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'showmen_inflatables',
    name: 'Inflables en Pista',
    category: 'entretenimiento',
    icon: 'fa-dragon',
    defaultW: 2,
    defaultH: 2,
    shape: 'rect',
    color: '#7c3aed',
    defaultChairs: 0,
    description: 'Inflables de showmen en pista.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'limo',
    name: 'Limusina',
    category: 'entretenimiento',
    icon: 'fa-car-side',
    defaultW: 6,
    defaultH: 2.5,
    shape: 'rect',
    color: '#1f2937',
    defaultChairs: 0,
    description: 'Limusina de lujo.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'photo_firma',
    name: 'Foto Firma Caballete',
    category: 'entretenimiento',
    icon: 'fa-image',
    defaultW: 1.2,
    defaultH: 0.8,
    shape: 'rect',
    color: '#92400e',
    defaultChairs: 0,
    description: 'Caballete con foto firma.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'projector_screen',
    name: 'Pantalla Proyección',
    category: 'entretenimiento',
    icon: 'fa-tv',
    defaultW: 3,
    defaultH: 2,
    shape: 'rect',
    color: '#1e293b',
    defaultChairs: 0,
    description: 'Pantalla de proyección / LED.',
    layer: 'entretenimiento',
    planoOnly: false
  },
{
    type: 'centerpiece_tall',
    name: 'Centro Mesa Alto',
    category: 'decoracion',
    icon: 'fa-seedling',
    defaultW: 0.3,
    defaultH: 0.3,
    shape: 'circle',
    color: '#166534',
    defaultChairs: 0,
    description: 'Centro de mesa alto floral.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'centerpiece_round',
    name: 'Centro Mesa Bajo',
    category: 'decoracion',
    icon: 'fa-circle-dot',
    defaultW: 0.4,
    defaultH: 0.4,
    shape: 'circle',
    color: '#166534',
    defaultChairs: 0,
    description: 'Centro de mesa bajo redondo.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'centerpiece_long',
    name: 'Centro Mesa Largo',
    category: 'decoracion',
    icon: 'fa-minus',
    defaultW: 1,
    defaultH: 0.2,
    shape: 'rect',
    color: '#166534',
    defaultChairs: 0,
    description: 'Centro de mesa largo horizontal.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'flower_arch',
    name: 'Arco Floral',
    category: 'decoracion',
    icon: 'fa-archway',
    defaultW: 3,
    defaultH: 2.5,
    shape: 'arch',
    color: '#f472b6',
    defaultChairs: 0,
    description: 'Arco floral decorativo.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'balloon_arch',
    name: 'Arco de Globos',
    category: 'decoracion',
    icon: 'fa-circle',
    defaultW: 3,
    defaultH: 2.5,
    shape: 'arch',
    color: '#a855f7',
    defaultChairs: 0,
    description: 'Arco de globos decorativo.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'backdrop',
    name: 'Fondo Fotográfico',
    category: 'decoracion',
    icon: 'fa-image',
    defaultW: 3,
    defaultH: 2.5,
    shape: 'rect',
    color: '#374151',
    defaultChairs: 0,
    description: 'Backdrop / fondo para fotos.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'shrub',
    name: 'Arbusto Decorativo',
    category: 'decoracion',
    icon: 'fa-tree',
    defaultW: 1,
    defaultH: 1,
    shape: 'circle',
    color: '#166534',
    defaultChairs: 0,
    description: 'Arbusto o planta decorativa.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'arch_decor',
    name: 'Arco Estructural/Salón',
    category: 'decoracion',
    icon: 'fa-archway',
    defaultW: 2.5,
    defaultH: 3.0,
    shape: 'arch',
    color: '#cbd5e1',
    defaultChairs: 0,
    description: 'Arco decorativo o columna de salón.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'tree_decor',
    name: 'Árbol Decorativo',
    category: 'decoracion',
    icon: 'fa-tree',
    defaultW: 1.5,
    defaultH: 1.5,
    shape: 'circle',
    color: '#15803d',
    defaultChairs: 0,
    description: 'Árbol decorativo mediano.',
    layer: 'decoracion',
    planoOnly: false
  },
{
    type: 'vendor_paletas',
    name: 'Paletas La Princesa',
    category: 'proveedores',
    icon: 'fa-ice-cream',
    defaultW: 2,
    defaultH: 1.5,
    shape: 'rect',
    color: '#f472b6',
    defaultChairs: 0,
    description: 'Carrito de paletas La Princesa.',
    layer: 'proveedores',
    planoOnly: false
  },
{
    type: 'vendor_taquiza',
    name: 'Carrito de Taquiza',
    category: 'proveedores',
    icon: 'fa-fire-burner',
    defaultW: 2,
    defaultH: 1.5,
    shape: 'rect',
    color: '#b45309',
    defaultChairs: 0,
    description: 'Estación de taquiza.',
    layer: 'proveedores',
    planoOnly: false
  },
{
    type: 'vendor_mariachi',
    name: 'Mariachi',
    category: 'proveedores',
    icon: 'fa-guitar',
    defaultW: 3,
    defaultH: 2,
    shape: 'rect',
    color: '#c9a96e',
    defaultChairs: 0,
    description: 'Espacio para mariachi.',
    layer: 'proveedores',
    planoOnly: false
  },
{
    type: 'vendor_banda',
    name: 'Banda en Vivo',
    category: 'proveedores',
    icon: 'fa-drum',
    defaultW: 4,
    defaultH: 3,
    shape: 'rect',
    color: '#7c3aed',
    defaultChairs: 0,
    description: 'Espacio para banda en vivo.',
    layer: 'proveedores',
    planoOnly: false
  },
{
    type: 'vendor_saxo',
    name: 'Saxofonista',
    category: 'proveedores',
    icon: 'fa-music',
    defaultW: 1.5,
    defaultH: 1.5,
    shape: 'circle',
    color: '#d97706',
    defaultChairs: 0,
    description: 'Espacio para saxofonista.',
    layer: 'proveedores',
    planoOnly: false
  },
{
    type: 'cart_esquites',
    name: 'Carrito de Esquites',
    category: 'proveedores',
    icon: 'fa-cart-shopping',
    defaultW: 2.0,
    defaultH: 1.2,
    shape: 'rect',
    color: '#eab308',
    defaultChairs: 0,
    description: 'Estación móvil / carrito de esquites y elotes.',
    layer: 'proveedores',
    planoOnly: false
  },
{
    type: 'vendor_generic',
    name: 'Proveedor Genérico',
    category: 'proveedores',
    icon: 'fa-store',
    defaultW: 3,
    defaultH: 3,
    shape: 'rect',
    color: '#374151',
    defaultChairs: 0,
    description: 'Proveedor o estación genérica.',
    planoOnly: false
  }
];

console.log('[elements-db] Loaded', window.ELEMENTS_CATALOG.length, 'element types across', Object.keys(window.ELEMENT_CATEGORIES).length, 'categories.');
